name: researcher

description: Example demonstrating how to use the library merging_builder.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.3.1
  researcher_builder:
    path: ../researcher_builder

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.5
  lints: ^2.0.1
  source_gen: ^1.2.6
  test: ^1.22.1

dependency_overrides: null

# source_gen:
#   git:
#     url: git@github.com:dart-lang/source_gen.git
#     ref: master
#     path: source_gen
